### ISSUE TITLE
Solving image puzzle with python and Selenium

### ISSUE THREAD

**Issue by gcart2** [ZennoLab/capmonstercloud-client-python#17]
I'm trying to solve the image puzzle using the following code 

    token = driver.find_element(By.ID, "g-recaptcha-response")
    url = driver.find_element(By.CSS_SELECTOR, 'iframe[title="reCAPTCHA"]').get_attribute('src')
    site_key = url.split("&")[1][2:]
    req = RecaptchaV2ProxylessRequest(websiteUrl=driver.current_url, websiteKey=site_key)
    responses = asyncio.run(solve_captcha(req))
    driver.execute_script(f"arguments[0].innerHTML = '{responses['gRecaptchaResponse']}';", token)

But this wasn't working, some times the image challenge popup, than I changed the code to the following

    token = driver.find_element(By.ID, "g-recaptcha-response-1")
    url = driver.find_element(By.CSS_SELECTOR, 'iframe[title="reCAPTCHA"]').get_attribute('src')
    site_key = url.split("&")[1][2:]
    req = RecaptchaV2ProxylessRequest(websiteUrl=driver.current_url, websiteKey=site_key)
    responses = asyncio.run(solve_captcha(req))
    driver.execute_script(f"arguments[0].innerHTML = '{responses['gRecaptchaResponse']}';", token)
    driver.switch_to.frame(captcha)
    time.sleep(1)
    driver.find_element(By.XPATH, '//*[@id="rc-imageselect"]/div[3]/div[2]/div[1]/div[2]').click()
    driver.switch_to.default_content()

Which result in the following 
![image](https://github.com/ZennoLab/capmonstercloud-client-python/assets/148389049/2e633311-1da9-4ce6-8877-7d9a0c431566)

How can I properly solve it ?

**Comment by azeriker** [comment]
Ask in support we will help https://helpdesk.zennolab.com/conversation/new
