### ISSUE TITLE
Code Block in Examples is Not Working 

### ISSUE THREAD

**Issue by brngylni** [ZennoLab/capmonstercloud-client-python#2]
A code block in the examples part and also in the official website is not working. There is a type mismatch between the two lines.

`
client_options = ClientOptions(api_key=API_CAPMONSTER)
cap_monster_client = CapMonsterClient(options=client_options)
`

When you send the options to CapMonsterClient constructor, it raises an error:
![resim](https://user-images.githubusercontent.com/66281850/196883478-bbca51de-9e05-4674-bfad-27fa11f3f350.png)

Because the CapMonsterClient constructor is defined as:

`
def __init__(self, options: Type[ClientOptions]) -> None:
    self.options = options
`

**Comment by greenberd09** [comment]
Hello @brngylni 
Really, ure right. Client options client is not it own instance. 
I updated the client according to the [fixes](https://github.com/ZennoLab/capmonstercloud-client-python/pull/3).
Just update your capmonstercloudclient to 1.0.1.
Thank for you contributing.

**Comment by greenberd09** [comment]
@brngylni 
Did this solve your problem?

**Comment by brngylni** [comment]
> @brngylni 
> Did this solve your problem?

Yes. I have another problem which it can't solve recaptchav3 but I don't think that is related with this

**Comment by greenberd09** [comment]
@brngylni ok, then could you please open another issue with a bug report.
