### ISSUE TITLE
Set UserAgent header for diagnostic purposes

### ISSUE THREAD

**Issue by george-tsaplin** [ZennoLab/capmonstercloud-client-python#4]
Clients for other languages set UserAgent header.
For example https://github.com/ZennoLab/capmonstercloud-client-dotnet/blob/a640e8317c16e829104b1c605b6d7842a35cf0a3/CapMonsterCloud.Client/CapMonsterCloudClientFactory.cs#L75
UserAgent must be unique for python, it MAY be "Zennolab.CapMonsterCloud.Client.Python/{client version}"

**Comment by greenberd09** [comment]
Hello
Set header User-Agent was added in this [request](https://github.com/ZennoLab/capmonstercloud-client-python/pull/5/files#diff-7274980da0e0e8b0904eb86b8bcfc503cb57748470f3ed804297da5d5cbe78ddR32) as {"User-Agent":"Zennolab.CapMonsterCloud.Client.Python/{client version}"}
